apiVersion: v1
data:
    password: ENC[AES256_GCM,data:yQv562ugr4wmvc7l,iv:Mz2TA73lg8wbOQ6H56JwYwwmL3D8CBFEGGw+6bhPq3k=,tag:Q/Vql3VyXb7hk+AkEMD6ZA==,type:str]
    user: ENC[AES256_GCM,data:sKTZL8/DiLY=,iv:P6ZcgTLIOUEvbgLuIjgJaOj/VEAvbT00rtDqLGKcU5Q=,tag:xZGooxC4u7Ey186dwycVng==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bWFNK1R4RGMxWDY1MTFC
            ZXJ4TnB2TGFGTW5IUW9FOXM0MFdmanR2MndrCnRwc2JpU2lJclNOY25oeXoyWUFh
            SHpKaWlsM01BblFMZmxEU0QwbCtyZjgKLS0tIHEzL21IWTFWRTFLMDZ3aTR0SG5m
            a1NzMnhrWGRHNFhvcUpFVjRvSkh5M0UKt35Q7CRIM+3TCan4f5THPPDnkzDPoIVi
            pQypsmNjcyl1S+BoejQXoiO13MAEqOanZUmpATrP0W3TGhH9C+M8ww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14uxue36c7l29wj2x6aqj6qs3np8j0jfp3qwf6may3gwwphs2jfeqqzjp63
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T04:29:19Z"
    mac: ENC[AES256_GCM,data:vQ1wdU6/Xoc00C3vPpnc9XwcqnzoHR4MMSg/Jj7UYCxuGTEjXdTWicP3CNM7aFUMDJ6mSMq0HnAfjOkIfRR+weIIZ9MXAxuh8NFlUhSrmJGHUC1xf8RuCwVeuBvnAKoUvcGaTU2DNWBb89T+/Rhy36L05bGSYcY+yJnbEey4+3c=,iv:ooP7b+QQpPUkSc8I2NjmIBahrX5/HURFK9LVdsd8Wr8=,tag:RTSJ0DrJPRf+brpkKSSLbA==,type:str]
    version: 3.13.2
