apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:kYQclehdTbWgQLK2,iv:4r6B1YFyXfs+U/L6mrwYO7M99olb0QJnhSpsmZEpblk=,tag:Luk7278YWdSoAarF6Qvceg==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:6PMEBVM5ma+qrpvS,iv:2lL/FVrYzcV+2LD6Qi85qMrwukyxxtiU3qRpbdOAL3Q=,tag:jon4COUudONGDTErYp3UDg==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQXZObTZEdEVVdU9zTnB1
            U0kxcW5CeU0zdmh1TnFOL1Ywamh4Vm43TEdZCk44TjBQbUt4TEh2cjcvejlJQXQz
            SnVkV29UZDd1TEFaY2FUaC9FbEFaUmMKLS0tIDZ4WW5nSmJBTG00NWp6eWVnL1Fl
            V3BMVmx5SndxUmNnaklrMlF0N3B3eXcKjdxwVsGRms4D4kmaMqk3B4YT9JyllweJ
            UvOmCw2pGWjGg3jolhJarrG4IY6NySKMjpu+HAWWZFT2zWt2osZCCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14uxue36c7l29wj2x6aqj6qs3np8j0jfp3qwf6may3gwwphs2jfeqqzjp63
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T11:35:44Z"
    mac: ENC[AES256_GCM,data:N+vOzlNWbpepk+XH7H/y90527tJzh4j/gKYv6mbGHRjp2ARaCD4xswNQub92pesO8mL5o2JEe4ZRr7WiFPD39Dg1HKDI+X1yx3W5hY6Krzt59va6MTIR7gNh5IQBISThOIz6wGmpjxIRFWlLL98S797eJv5ULuDlt5L3o2YbXFk=,iv:rN6rN6jrQ1ki7UuX33UFDE1O0ApUJHPD0QQOID98Y7w=,tag:do/r4jH3hxoXn1APwcmZhQ==,type:str]
    version: 3.13.2
