apiVersion: ENC[AES256_GCM,data:75g=,iv:1rWdc0IPM0Lt73cvilJTfP993761QwjexfgCRGDrWQU=,tag:l0LpHbYzFsWYWseqDIDm8g==,type:str]
data:
    credentials.json: ENC[AES256_GCM,data:0Q+G2OiVZTxOtIPOZH6gRF+GPzGwusfaeZ2PyNtDh4mhc6oz6lqQdJ4qi6a2RgG8URut1CBKRnhumcWzrK0rLYMxSxB3XbG+iw27Hanh/UdZV7Fa52h/UO8mGQDF9F+/2UWDmImmGWQChrhwurY0C1BVhkTvxc9gTG/UbqEHDvto0UAyJb52NrLuYzBxkiBcHP8zkL5PoGMv4OhpdA/a6nMqE3p0BJriY1jUKKyW5JbAZ7ZipLtjFo33F1IeEoJad01rYxgDSbJYnoeD3/cTAIDir6klr//9Zr2TOEABnIia6DDEbgh7fWiPOCQ=,iv:bP/84/3IuknFPtBPKAngYCmKpF1T29aiZfbow2xdkBk=,tag:55ZnhZRSRjdz2FpIOaQ20A==,type:str]
kind: ENC[AES256_GCM,data:JzHPNUfs,iv:M/iv3pFu1oCLkrrAlEr3VdSQlfQXjMrHPRqH8WN7Zog=,tag:Jrz4PyhpON1Shdpbg7R/cw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wOHSUfwyc9x1+QgEeQblLhmf,iv:GQzGvo2InhlnnxnWt2FHJZnVSwNq02cHY1q78L5KwWA=,tag:HZqkyaJC8mkS9N5pznD+EQ==,type:str]
    namespace: ENC[AES256_GCM,data:KZHIOWxLZ7OGgAI=,iv:hHrjFFNcGbqpLLFPXLr33m8QdL7ckfMpOA+NttB6gTE=,tag:39D6TG6Gn/pNX9xssEp1Hw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUG4xQTU4TVVjYzZVek4v
            SWRESjB0MExFSDhLbGNYeEV0M2I0bkpYaUNVCjdHMFg5T3VQbUlEcjFUTzl6L0xP
            bGdlWnNOa3N2bHdsTXR1dENrVWVPU2sKLS0tIFpPK3lXRkJKWkdQdEVCVWMrRklI
            YmVNMWd3aDRKU1dnMHVja1FFM1g4d2MK2Yk/tLWzkf35vrAZXBcpW+m9jBpH2TjC
            Q1Q8Hc1JzESveiSTp3cwEDLvrjrzHu6miV2oMO75yPcr/Jekr3dDYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14uxue36c7l29wj2x6aqj6qs3np8j0jfp3qwf6may3gwwphs2jfeqqzjp63
    lastmodified: "2026-07-11T07:00:34Z"
    mac: ENC[AES256_GCM,data:e7RGgwVRlU65heFzcICn2GXWr5Sg814maEoBb2jzH7toKJDLFNroCZsqF730ydkteTKA5xDLhISTitg7GjX0V/dehJtkJMVgkN1mMgT03CZmyUTB2so5+admApXH4e9LhPwl8safT/WkmxPv4XgBzmPxoPc3/Psuvogaa4SBbvc=,iv:IkTkvLNFGQtIjvb1P0Xa/mMOQIkxXhFfpRT+2TiGW5g=,tag:/gaAoWvu731caZV8Omg6MQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
