apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:muTI1YO+HX5p0qm5MRaYujdMYeZoxnxllnCm7CSddnhtQIc9+KwW6ZoBO0q3PSiWN6vGWbQEj4+BO9gBA3QmVhtEhpEBNs+nVBCjR6bQLnl54cqDc5pP3XzorXB0FMA/QVQ7Ow3lSoVm5jsorZjghUcpdejrrCNIV3+5Wq0Ujbu0Z5/jxt00U4HDtErBcFL2UvB3OH5FO+05o8cfzWWTHpEL40SIxfmejza0iOnccaF/c2ZmvX/+ixNvpnB5VDyGuOhH+ViIgrvQOyCzocyPmgXonF8a+ukF4cpSgUTFA+Q0mUMAHFVit5KCv10=,iv:3wV7hThWiyxOh6nr5R17ZswWiJkr84w3zZ5RvRtV9OQ=,tag:YiC+i6wO9KzsyT2JY/W27A==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: linkding
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwK2JEQjRkUFowMTlGNWlW
            YlZGNEFpQUdSQXFsMlYrOUVxRlZ5ek9LN3pNCnNtOXRhUlJYUzEzREs5NFlFYXox
            OE03TG5NVEdZNi9RWjB4emZuWFV6NzgKLS0tIFFMTlRYRmlBcHFxc2hBVmJ0czhw
            NTRIWDRSaEFoRzBURmJSMkRoQWZ6RkUKqx4EJijYPZDEgsBfJ/4s9ugaU+tuCFKY
            WRJslKn9xvLS++WV8PgLT6x5kJK1kAJXmtJYAk/qNJmQh+8H2PEp4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14uxue36c7l29wj2x6aqj6qs3np8j0jfp3qwf6may3gwwphs2jfeqqzjp63
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T15:43:26Z"
    mac: ENC[AES256_GCM,data:wGH69/hyPLxthZ8b/1WN0iAkPC00fZT1/mCTbUUbwcnUhqCWlVQc9CplmuNut/vlAN7v8wvk5JqUhG2T2dity2e54W9cZVuD2/wKSveqYHzVVGb6uCmqcjMeJ696/ZQq8HQ0O+He7ZNQVKBjhgKraGt/Y/0zUVhtRGzeeDQ27QM=,iv:zYHCRUIy+Kuc71uuQBcYLbQ/F9iNS4sR4dLS3o7+KqQ=,tag:5c2Y5v95KXvRZhAkRgdEsQ==,type:str]
    version: 3.13.2
